### ISSUE TITLE
Daily reminder doesn't work

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitrpg-android#100]
I activated the daily reminder but never got a notification

**Comment by veeeeeee** [comment]
Have an email reporting that the user got one notification, but not since then.

**Comment by wizonesolutions** [comment]
This is still not working for me at any time. It actually used to work until 5-7 days ago from now. So I've missed my dailies 2-3 times :(

**Comment by Data5tream** [comment]
@wizonesolutions, this was fixed after [version 0.0.24](https://github.com/HabitRPG/habitrpg-android/tree/0.0.24) was released. It's currently not in stable :confused:

**Comment by wizonesolutions** [comment]
A HabitRPG Beta on Google Play would be great (in order to get some fixes sooner).

**Comment by deathau** [comment]
I just want to point out that I was the one with the email veeeeeee received (at least I think I was) and I am no longer experiencing this issue.
