### ISSUE TITLE
bug?  Create account on app -> See flags.welcomed "Welcome to Habitica" intro screen on website

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitrpg-android#128]
I'm not sure if this is supposed to occur or not.

I created an account on the app.

I then logged in to the account on a browser, and saw the "Welcome to Habitica" screen:

![screen shot 2015-12-08 at 7 25 10 pm](https://cloud.githubusercontent.com/assets/1495809/11652731/1cb9d3dc-9de5-11e5-9f31-5cac257a6472.png)

This is the screen that's controlled by the `flags.welcomed` flag.

**Comment by lemoness** [comment]
We decided to leave it until we have the Android tutorial in.
