### ISSUE TITLE
UI fix: level up modal

### ISSUE THREAD

**Issue by veeeeeee** [HabitRPG/habitrpg-android#133]
![image](https://cloud.githubusercontent.com/assets/5608909/11656295/0b730ae8-9d69-11e5-84fd-77d31c3b1a0b.png)

At least center the text and add more space between avatar and text?

**Comment by Data5tream** [comment]
If the app follows the [design guidelines](https://www.google.com/design/spec/components/cards.html#cards-content-blocks), if think that it shouldn't center the text...
