### ISSUE TITLE
Add copy to gem purchase screen

### ISSUE THREAD

**Issue by veeeeeee** [HabitRPG/habitrpg-android#156]
![tempfileforshare](https://cloud.githubusercontent.com/assets/1495809/11761397/c2fe9e56-a10c-11e5-99bb-03c79ab117c9.jpg)

**Comment by lemoness** [comment]
So, this copy will only make sense once some of the purchasable things are in the app.We may want to put in several edited version as we expand the number of purchasables available.

"Want to help us keep Habitica running? You can support the developers by buying gems!

Gems allow you to buy fun extras for your account, including:

- Cool costumes for your avatar
- Awesome backgrounds
- Fun quests that reward you with pet eggs
- The ability to change your class before level 100

Thank you so much for helping us make Habitica the best it can be. Your support means a lot to us!"

Feedback welcome.

**Comment by negue** [comment]
Should this text also get translated to other languages?

**Comment by lemoness** [comment]
Yes, definitely!
