### ISSUE TITLE
various crashes: "Unfortunately, Habitica has stopped" and "Connection Errors" and "Habitica isn't responding"

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitrpg-android#157]
I seem to be getting crashes more often than other users, so I'm going to start documenting them here. @franzejr says that my crashes are being logged.

So, I got "Unfortunately Habitica has stopped" when logging out, about three to five minutes before the timestamp of this post. 

New crashes will be in the comments here.

**Comment by franzejr** [comment]
This issue still happening? Some update?

**Comment by Alys** [comment]
Much less than it used to. I was just reporting them in case knowing the
times they happened was useful. I'm happy for this to be closed if you
don't need it.

**Comment by binamkayastha** [comment]
This keeps happening to me when I run the program from Android Studio. It fails every time I login. I've wanted to help with issues, but I can't get even login without crashing. Anyone know what it could be?

**Comment by vIiRuS** [comment]
In Android studio you have the android console, which shows you logs from the device. When the app crashes there usually is an error message as to why the app crashes. That should at least hint you towards the reason it crashed
