### ISSUE TITLE
Checklists on To-Dos and Dailies are not sorted

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitrpg-android#161]
On To-Dos and Dailies that have a checklist, the items are displayed in the opposite order to the website.

**Comment by stuffity** [comment]
When returning to the website, the order has been reversed on the website as well. Website and app now match each other, but do not match the user's preference.

**Comment by vIiRuS** [comment]
The checklist order isn't stored in the local database. Will need an additional order field, that is populated similar to how it is populated for tasks.

**Comment by dbarnett** [comment]
Yeah, I noticed that just creating a checklist like "A", "B", "C", "D", "E", the order immediately changed to something completely randomized like "D", "A", "C", "E", "B".

**Comment by vIiRuS** [comment]
Is this still happening for you with the most recent app version? It should be fixed there.



On 30 January 2016 at 22:16:24, David Barnett (notifications@github.com) wrote:

Yeah, I noticed that just creating a checklist like "A", "B", "C", "D", "E", the order immediately changed to something completely randomized like "D", "A", "C", "E", "B".

**Comment by dbarnett** [comment]
Ah, you're right. I was for some reason running a build from last Dec in the emulator where I tried it (0.0.24), and the latest version isn't showing any ordering problems for me.
