### ISSUE TITLE
Tasks (Dailies / To-Dos, maybe others) reorganise themselves (not just when completing them)

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitrpg-android#190]
Comments from various users:

- "Dailies are reorganizing themselves before my eyes. Very inconvenient as a daily originally at the bottom will jump to the top as I try to tap on it. I'm using a Galaxy s3, android version 4.4.2." -- https://mail.google.com/mail/u/0/#inbox/1518e6602e1099f7
- "Hi, I am having some trouble with my dailies, when I check items off a checklist it bumps the corresponding daily up to the top of the list." Phone is a OnePlus One running Android 5.1.1 and CyanogenMod 12.1-- https://mail.google.com/mail/u/0/#inbox/1519089e7d584337
- "I have also noticed my to-dos getting out of order. I can't remember exactly what happened but I edited a few and then when I checked one off the others would move toward the top (not just checking off the checklist but actually checking off the to-do without a checklist did this)" - Same user as above. Phone is a OnePlus One running Android 5.1.1 and CyanogenMod 12.1 -- https://mail.google.com/mail/u/0/#inbox/1519089e7d584337
- possibly related: https://github.com/HabitRPG/habitrpg-android/issues/174 "Checking off dailies moves some dailies to bottom of list but not others"
- "dailies sometimes reorder themselves" -- https://mail.google.com/mail/u/0/#inbox/15190ed93d2ff395
- "The order of items in Dailies doesn't match the old app and online (which do match). Also, in one case when I checked an item off it jumped up to second place in the list, though others haven't moved when checked (which is what I prefer)." -- https://mail.google.com/mail/u/0/#inbox/15197f3cbe9cb8fe

**Comment by vIiRuS** [comment]
This probably also affects rewards
