### ISSUE TITLE
ticking one checklist item closes the checklist

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitrpg-android#214]
"When checking 1 item in a checklist, it goes out of the list back to the "dailies" menu, instead of remaining in the specific item's checklist. This kills the flow" -- https://mail.google.com/mail/u/0/#inbox/15195394deae243f

Confirmed on my phone. It's inconvenient because you're often actioning several checklist items from the one Daily at the same time.

**Comment by mchoochoo** [comment]
Hi, I'm new to Github and Habitica... I'm still having this issue on my Android phone.  It says it was resolved a long time ago, though?
