### ISSUE TITLE
various feature requests

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitrpg-android#215]
Miscellaneous feature requests from emails, because I don't want to fill up the issues with one for each until you're ready to work on them (but feel free to split this up if you prefer an issue for each):

- [ ] 1. **Buffs** - "I would like to have an information about being buffed"
- [x] 2. **Menu button for left-side menu** -- "The menu button does not work (I am using the Galaxy S4). It would be nice to see the menu, like when swiping from the left edge." _[I agree!]_
- [x] 3. **Keyboard hiding** - "on party chat, after I send the message, the keyboard should hide." _See also https://github.com/HabitRPG/habitrpg-android/issues/172 "Keyboard should close when switching view"_
- [ ] 4. **Streaks** - "Please add it so that it shows counts for continuous dailies done in a row!"
- [ ] 5. **Mounts for Party** - "When I go to Party->Members, I don't see mounts." (_I've seen that comment two or three times, but it's funny - no one ever comments on the lack of pets or backgrounds._)
- [ ] 6. **Ticked Dailies not clear enough** - "One issue is that the visual messaging doesn't seem to be clear when I tick vs. Untick a daily. I installed the app when I already had a number of ticked dailies for the day." -- I'm seeking more feedback about this. https://mail.google.com/mail/u/0/#sent/1518f8fc3f3dbcde
- [ ] 7. **Headings in menu** - could be clearer that they are headings? - "Inventory is not loading, it's slightly greyed out."
- [ ] 8. **FAB for adding items has usability problems** - "While looking at my TODOs, I click the bottom-right + icon. I am disappointed that the + icon forces me to again choose a task type instead of creating a TODO (or whatever other task type I am currently browsing). Also, if I mis-tap when aiming for + New Habit, I will edit whatever task is underneath my finger. That seems distracting."
- [ ] 9. **Sound effects** - "please add the sounds from habitica website... They are now connected in my brain with positive motivation."  -- I know this might seem like a minor feature, but that comment about motivation is interesting and valuable. Triggers and rewards are an important part of productivity, and if the sound effects on the website have become integral to your motivation, it would be disappointing to not have them in the app too. I'm thinking this might be a feature we'd want to add sooner rather than later, if it's not too difficult to implement.
- [ ] 10. **Reminders** - "multiple reminders through out the day instead of just one reminders for dailies!"
- [ ] 11. **Results of completing tasks could be clearer** - "Better view of the points that get updated and pictures of the Drop items"
- [ ] 12. **Ability to move tasks to a different sort order**
- [ ] 13. **Use slide-down to sync tasks** -- "have a Task page refresh with a slide down method (like the Party page Chat refresh method)!"
- [ ] 14. **Quest invitation accept/reject**

**Comment by Petemir** [comment]
Hi. Could we add to the "multiple reminders" thing, to be able to set due date for ToDos in the app and make a reminder based on it?
