### ISSUE TITLE
When completing a task and getting a drop, stats change isn't shown (XP/Experience, GP/Gold, etc)

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitrpg-android#235]
From [email](https://mail.google.com/mail/u/0/#inbox/15199611ba18f2fb):

"**when a task is completed and you receive an item, it doesn't appear how much gold and experience you get.**"

Possibly related: https://github.com/HabitRPG/habitrpg-android/issues/233 "When completing a task, the stats change isn't always shown (XP/Experience, GP/Gold, etc)"

**Comment by negue** [comment]
yes the snackbar can only show one :D ... we need to time those snackbars
