### ISSUE TITLE
Checklist items reordering themselves

### ISSUE THREAD

**Issue by stuffity** [HabitRPG/habitrpg-android#279]
Possibly the same as or related to #161 and/or #190.

Items within checklists are reordering themselves, mostly in reverse order (as in #161), but an occasional item will be moved to a random location in the list.

**Comment by Alys** [comment]
Reported again in https://github.com/HabitRPG/habitrpg-android/issues/363 with an example of the changed sort order and with this:

"I've sorted it back into the correct order twice now on different days. I thought it held the first time, but the second time I did it, it only held long enough for me to check one off, and then it was back in the incorrect order."
