### ISSUE TITLE
App flagged as adware/malware in AVG

### ISSUE THREAD

**Issue by veeeeeee** [HabitRPG/habitrpg-android#286]
I have reached out to AVG through their app to see what can be done. Will update here when there is movement.

**Comment by dlew** [comment]
This is a common problem with AVG (which I and many other developers have run into). AVG tends to have a ton of false positives when it comes to their scanner. It's basically junk.

That said, if you care enough, you can try to get whitelisted by AVG: http://www.avg.com/submit-sample

Alternatively, you may need to use this form: https://support.avg.com/support_contact_form?l=en_US&retUrl=support_Android_AVG_Antivirus_Free&prod=AVG%20AntiVirus%20FREE

**Comment by veeeeeee** [comment]
@dlew Thanks for the support! I've contacted them through that first form, but will also try the second.

**Comment by veeeeeee** [comment]
Have gotten reply requesting a screenshot, which was helpfully sent in by one of our users!
