### ISSUE TITLE
Checklist of Task at bottom of screen opens off screen--adjust to scroll into view

### ISSUE THREAD

**Issue by veeeeeee** [HabitRPG/habitrpg-android#288]
"When you open up the checklist of a daily in the bottom position, the checklist opens but you can't tell because it's off-screen. It would be really nice if opening the checklist triggered the dailies list to scroll so that you could see the list immediately. Otherwise it's hard to tell if the checklist even opened."

**Comment by wwenbow** [comment]
I can try this
