### ISSUE TITLE
Health/Exp/Mana bars should display as empty when initialized

### ISSUE THREAD

**Issue by vIiRuS** [HabitRPG/habitrpg-android#329]
Instead of displaying as full, the bars should display as empty when they are created/ have values of 0/0.

Reasoning: When the app launches and the first thing the user sees is decreasing bars, that doesn't feel very good. having them grow from 0 looks better.

**Comment by Data5tream** [comment]
A bit of topic:
What do you think about [moving the header into the drawer](https://github.com/mikepenz/MaterialDrawer#can-i-use-my-own-drawerlayout-implementation) instead of expanding the action bar?
