### ISSUE TITLE
Emoji and markdown support

### ISSUE THREAD

**Issue by vIiRuS** [HabitRPG/habitrpg-android#333]
- [ ] Tasks
- [ ] Party description
- [ ] Chat

**Comment by Alys** [comment]
https://github.com/HabitRPG/habitrpg-android/issues/164 :)

**Comment by Data5tream** [comment]
I've almost finished [emoji support](https://github.com/Data5tream/habitrpg-android/tree/emojis). Only party description is left (app crashes when I try to access the description, I'm not in a party). I'm thinking about using [this library](https://github.com/commonsguy/cwac-anddown) to parse the markdown. 

What do you think?

**Comment by vIiRuS** [comment]
Awesome!

My concern with that library would be performance. In the case of tasks and chats, it would have to render multiple html strings.
In the Readme they recommend bypass if you want to put the text directly into a TextView, which is what we are doing. Maybe that one is better in our case? https://github.com/Uncodin/bypass

If the performance with cwac anddown is good, I don't have any objections.

**Comment by Data5tream** [comment]
I just finished my test with the emojis and was looking to setup the markdown parser and you're totally right. Bypass is not only faster ([here's a benchmark](https://github.com/Uncodin/bypass/blob/master/platform/android/README.md#speed)) but also actively maintained. I'll use bypass!

Maybe you can have a look at my emoji branch? I just can't find out why it crashes when replacing `TextView` with the emoji parsing `EmojiconTextView`  :confused:

**Comment by dlew** [comment]
We're using Bypass at Trello. I am not sure I would call it "actively" maintained. The maintainer is accepting pull requests but a release hasn't been made in years. If you want to use the latest code (which I recommend, since I added support for a variety of missing tags) then you will have to compile Bypass yourself.

It's been a year since I looked into alternatives, things might have gotten better in another lib.

Regarding performance: I doubt that markdown will be the deciding factor there. The way Habitica is setup doesn't imply much rapid rendering of complex markdown. If it is a factor, then it's easy to make a cache of `String` -> rendered `CharSequence`.

**Comment by Data5tream** [comment]
Ok, I'll keep that in mind. I'm going to compile bypass myself.

**Comment by dlew** [comment]
I found instructions on how to get it building last time I worked on it; the information may be a bit out of date but it gives the overall idea of what's necessary.

------

1. Install Boost: www.boost.org
    (Easy mode: $ brew install boost)

2. Download NDK (32-bit version): https://developer.android.com/tools/sdk/ndk/index.html

    If it doesn't compile, you might have the wrong version!

3. Extract NDK and set $ANDROID_NDK_HOME to it.

4. Download Bypass source code: https://github.com/trello/bypass

5. Go to bypass/platforms/android/library and run `$ ndk-build`

6. Go to bypass/platforms/android and run `$ mvn install`

Note: if you run `$ mvn clean`, you must re-run ndk-build before trying to `$ mvn install` again.

**Comment by Data5tream** [comment]
Thank you @dlew! I was searching for what I've to do after step 5 :sweat_smile:
Builds are failing right now because of this:

    Exception in thread "pool-1-thread-2" Exception in thread "pool-1-thread-3" java.lang.NoClassDefFoundError: org/eclipse/aether/spi/connector/Transfer$State

I'll continue setting this up tomorrow.
