### ISSUE TITLE
Menu item header not headery

### ISSUE THREAD

**Issue by vIiRuS** [HabitRPG/habitrpg-android#338]
Multiple users gave feedback, that the "Social" and "inventory" buttons in the menu didn't work. As those are headers and not buttons, we apparently need to style them in a way that makes that clearer.

**Comment by michaldrabik** [comment]
A possible solution would be to add icons. Example from Material Design docs:
![](http://i.imgur.com/ZBxOGPT.png)

**Comment by ajfclark** [comment]
Are you using the standard  android.support.design.widget.NavigationView? If so, you can get the headings by grouping items in the xml. eg, something along the lines of:
```
<?xml version="1.0" encoding="utf-8"?>
<menu xmlns:android="http://schemas.android.com/apk/res/android">
    <group
        android:id="@+id/grp1"
        android:checkableBehavior="single">
        <item
            android:id="@+id/item1"
            android:icon="@drawable/ic_item1"
            android:title="@string/item1" />
        <item
            android:id="@+id/item2"
            android:icon="@drawable/ic_item2"
            android:title="@string/item2" />
    </group>
    <group
        android:id="@+id/grp2"
        android:checkableBehavior="single">
        <item android:title="@string/subheading2">
            <menu>
                <group android:checkableBehavior="single">
                    <item
                        android:id="@+id/item3"
                        android:icon="@drawable/ic_item2"
                        android:title="@string/item3" />
                    <item
                        android:id="@+id/item4"
                        android:icon="@drawable/ic_item4"
                        android:title="@string/item4" />
                </group>
            </menu>
        </item>
    </group>
</menu>
```
Each group needs a different id for the title to show.

**Comment by ajfclark** [comment]
I just updated to this release and it doesn't look very material now with the icons on the headings. Usually, the icons are for each item that's clickable and the headings have no icons. I'd also not expect to see the about heading at the bottom at all, especially with an actual about item at the bottom.
