### ISSUE TITLE
Aesthetic issues in latest update

### ISSUE THREAD

**Issue by Kathryn-the-Writer** [HabitRPG/habitrpg-android#358]
Great job, guys! Some things I spotted after the latest update:

1. Images in task names (e.g. :car:) don't show.
2. Dailies tab shows all tasks; no way to show only Due Dailies.
3. Rewards are in a weird order.

If you need any end-user testing, LMK. Happy to help. I love Habitica and use it all day, every day.

**Comment by vIiRuS** [comment]
Emojis is being worked on in #348 

#372
#190
