### ISSUE TITLE
Assign tasks to tags.

### ISSUE THREAD

**Issue by vIiRuS** [HabitRPG/habitrpg-android#361]
Currently you can't assign a tag to a task. That should be doable through the task form.

**Comment by WhatsEmo** [comment]
Hey, are there any preferences on where the "tag" selection should be in the UI? I personally placed it right under the Value TextView. Seeing that this is a month old, would you be fine waiting a few days before I send a pull request for this feature?

**Comment by vIiRuS** [comment]
on iOS it's the last item in the form. I think I'd prefer to also have it this way on android.

**Comment by WhatsEmo** [comment]
Currently there is an issue with TaskFormAcitivity.java aroun line 148 (Added a few @Binds)
tags = bundle.getStringArrayList("tagsId");

The tags variable is given an empty ArrayList even though I have multiple Tags defined on my account. I'll be looking into it; if you find a fix, please let me know!

**Comment by vIiRuS** [comment]
This seems to also (sometimes) happen for checklist items. Some users report that in the form the checklist is always empty for them.

**Comment by WhatsEmo** [comment]
Isn't it supposed to be always empty since the user must define it themselves? I'm new to Habitica, so I'm not too sure how the interaction goes.

**Comment by vIiRuS** [comment]
I apparently was a bit tired and misread the comment. that's something different than with the checklists.

In line 511 the tags list is queried from the database. As the query might not be instantaneous, it is executed asynchronously. The TransactionListener is needed to then use the response of the async query.

**Comment by WhatsEmo** [comment]
Finally finished implementing it! I'll be submitting a pull request soon.
