### ISSUE TITLE
Missing reward items

### ISSUE THREAD

**Issue by NathanMaton** [HabitRPG/habitrpg-android#371]
I see some reward items in the Android app but not the "Enchanted Armoire"  nor several other reward items that I see in the website for my level 30 character with uid: 2ab55d89-a3e5-4565-ba35-b6c9e145a60a

**Comment by Alys** [comment]
@NathanMaton We have the Enchanted Armoire bug reported at https://github.com/HabitRPG/habitrpg-android/issues/192
and I've just changed its title to indicate that other items are also missing. Could you please comment on that issue to state what the other items are?
