### ISSUE TITLE
The keyboard coming up for editing/creating tasks is kind of annoying

### ISSUE THREAD

**Issue by anuraags** [HabitRPG/habitrpg-android#376]
Do we need that keyboard to come up whenever we edit tasks?

Sometimes I want to just delete a task or change it's positive/negative property, and I find the keyboard coming up when I click on edit is kind of annoying.

**Comment by Data5tream** [comment]
Since I'm already working on keyboard and its behavior, should I fix this?

**Comment by vIiRuS** [comment]
Jeah, you can. It should still show up when a task is created, though.
So:
Task created -> behaviour stays the same
Task edited -> no keyboard popup when form is opened.
