### ISSUE TITLE
Use own (self-hosted) server

### ISSUE THREAD

**Issue by schmiegelt** [HabitRPG/habitrpg-android#383]
Is there any convinient way to change the server address in the app?

**Comment by vIiRuS** [comment]
Not with the distributed version. If you want to build it yourself, you can change the server address in the [strings.constants.xml](https://github.com/HabitRPG/habitrpg-android/blob/develop/Habitica/res/values/strings.constants.xml)

**Comment by schmiegelt** [comment]
OK, thanks.
Are there any plans to be able to change this from within the app, or is it too confusing for the average / new user?

**Comment by Alys** [comment]
We sometimes had problems with the old HabitRPG app because users ohanged
the server and then couldn't log in. This is not to say the option
shouldn't exist but if it does, it should be somewhat hidden and very
clearly labelled.

**Comment by schmiegelt** [comment]
Thank you for your help.

**Comment by Delath** [comment]
> Thank you for your help.

Sorry for the necro, but why did you close the issue?
It's 2024 and still there isn't a way to change the server address in the app...
I know that i can build it myself, but this way i would need to rebuild it each time an update comes out, doesn't seem very practical.

**Comment by lgwapnitsky** [comment]
> > Thank you for your help.
> 
> Sorry for the necro, but why did you close the issue? It's 2024 and still there isn't a way to change the server address in the app... I know that i can build it myself, but this way i would need to rebuild it each time an update comes out, doesn't seem very practical.

This is part of what's stopping me from self-hosting for friends/family
