### ISSUE TITLE
Health bars animate in party member list

### ISSUE THREAD

**Issue by patheticpat** [HabitRPG/habitrpg-android#388]
When I scroll through the list of my party's members, their health bars animate back and forth as the views are being recycled. I think this looks kinda confusing (since they aren't gaining or losing any HPs) and they shouldn't animate at all.

Should I work on this? It should be an easy enough task for a first contribution.

**Comment by vIiRuS** [comment]
Sounds like a good first contribution to me!
Ideally I would love it, if it could also be used for the header. So that there is a way to disable the animation. That way the initial value set on the header could be done without animation.

**Comment by patheticpat** [comment]
Great, I will look into this then.

**Comment by patheticpat** [comment]
I came up with a quick fix for the animation in the party member list. Should I open a pull request for it?
Ultimately I would like to make a custom `ValueBarView` that encapsulates everything that is in the `value_bar.xml` layout (i.e. the bar itself, the icon and the text) and then go from there in order to handle the animation.

**Comment by vIiRuS** [comment]
As long as the quick fix isn't a dirty hack, I'd be fine with having a fix now and a proper/better solution some time later. :)

**Comment by patheticpat** [comment]
Okay then, I didn't feel dirty writing it, but you be the judge. ^^
