### ISSUE TITLE
Auto-capitalize most text inputs

### ISSUE THREAD

**Issue by dbarnett** [HabitRPG/habitrpg-android#393]
Habitica doesn't seem to auto-capitalize any text inputs in the app. For most of them I intuitively expected them to capitalize the first letter I typed without me having to toggle caps on the keyboard.

**Comment by Alys** [comment]
Speaking personally, not as an admin:

I'd find that very annoying. None of my tasks now start with capital
letters. The website and API don't auto-capitalise so if the app did,
either tasks I enter there would be inconsistent with tasks entered from
other sources (which I'd find grating), or I'd have to always reverse the
capitalisation manually (which I'd grumble under my breath about every
time).

**Comment by dbarnett** [comment]
Websites never auto-capitalize because that's not how computer keyboards work. Most Android apps do. I don't know if it was an explicit choice or something they just inherited somehow, but e.g. when I go to create an event in Calendar it auto-capitalizes; same with an Inbox reminder or email subject. How is a TODO in Habitica any different?

I do find myself explicitly un-capitalizing in a lot of other apps. I know it's totally personal preference whether to capitalize these things, but it seems to be standard on Android to err on the side of capitalizing for inputs where sentences would be appropriate, or at least my user brain thinks that's the paradigm it's been trained with.

**Comment by dbarnett** [comment]
I hear your point about it being less convenient for anyone who prefers everything lowercase. Consistency with the website isn't any real basis though since there is no obvious way a website could auto-capitalize (force your caps lock key maybe?). I've never seen a website attempt anything like that and all of the equivalent Android apps I mentioned as examples work exactly like what you're referring to as inconsistent.

Anyway, I agree we need input from others and not just your preference against mine.

**Comment by dbarnett** [comment]
I also notice that the default tasks for a new account have the first letter capitalized:
<img width="897" alt="screen shot 2016-01-30 at 1 06 25 pm" src="https://cloud.githubusercontent.com/assets/65244/12698489/825a5630-c752-11e5-90a1-6f6972f2d2b9.png">

So while it's ultimately personal preference, if you're arguing for consistency I think the website doesn't support your case for no auto-capitalization.

**Comment by Alys** [comment]
Fair point about the default tasks.

"Android apps I mentioned as examples work exactly like what you're referring to as inconsistent." -- No, I was referring auto-capitalisation on the Habitica Android app as being inconsistent with the Habitica website and API, not inconsistent with other Android apps.

But yeah, we need a tie-breaker. :)  If no one responds, we can consider the default tasks to be the tie breaker.

**Comment by ExperimentMonty** [comment]
I also find it annoying that my tasks don't auto-capitalize the first letter when I'm adding new ones. I expect that on my phone, and it's jarring for me to look at my text after I've finished typing and notice that I need to go back to the beginning and fix a capitalization issue.

**Comment by Alys** [comment]
Fair enough. I withdraw my objection, especially since no one else has responded.
