### ISSUE TITLE
Log in with Facebook not working on Android

### ISSUE THREAD

**Issue by jeffrschorr** [HabitRPG/habitrpg-android#395]
I'm using a t-moible Samsung S6 Edge+ on the 0.0.25 version of the app released on Tuesday. Tapping the Facebook button seems to not do anything. The screen flashes like it is trying to log in, then nothing happens. 

Here's what I see:
https://youtu.be/1Xr416P8wjY

**Comment by vIiRuS** [comment]
I also noticed this and it will be fixed in the next update. I'll leave this issue open until then, so that other people can find it.
Note: There is no code fix needed for this. it was a configuration error during build.

**Comment by rmkoske** [comment]
Not sure if this is the same issue or different, but @sntk posted a similar issue to [HabitRPG Main](https://github.com/HabitRPG/habitrpg/issues).  Probably you know about it, but just in case I'll drop it here.  [Android App: Invalid App ID: CHANGE_ME #6602](https://github.com/HabitRPG/habitrpg/issues/6602)
