### ISSUE TITLE
Skills screen says "Unlock at lvl 10" instead of level 11

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitrpg-android#409]
When a low-level player uses the app, the Skills screen is unavailable with a message saying that skills unlock at level 10. It should say level 11.

We see a few questions in the Tavern from players who think there's a bug because they can't get to the skills screen at level 10.

**Comment by WhatsEmo** [comment]
The problem can be fixed by going to habitrpg-android\Habitica\res\values\strings.xml

/find "unlock_at_lvl_10" and change the value from "Unlock at lvl 10" to "Unlock at lvl 11"
