### ISSUE TITLE
UI: Single click '+' to add tasks

### ISSUE THREAD

**Issue by mrdanbrooks** [HabitRPG/habitrpg-android#410]
The current behavior of the '+' button is to bring up a secondary menu asking the user to select between adding a new 'habit', 'daily', 'todo', or 'reward'. While this is very functional, I think for many users _the expected behavior of this button is to simply add a new task task of the same type as whatever list they are current looking at_. 

I suspect that when users are on the todo tab they almost always choose to add a 'todo' when they press the '+' button, and when they are on the 'habits' tab the majority of the time they are wanting to add a habit, etc. The current behavior makes adding a task of any type a 2 step process instead of a one step process, and the smaller closely spaced menu items increases the likelihood of accidentally selecting a wrong item. This is not a big deal if you are only adding a single item, but for anyone adding multiple items (especially true for new users that are adjusting their lists frequently to match their needs, or anyone using the app as a todo list) this doubles the number of steps they have to take. 

The current behavior seem better suited for use in a combined view, where habits, dailies, and todos would all be shown together. In such a case, the intention of the user be more ambiguous and the menu would be better situated. 

I apologize for re-posting if this has been previous discussed elsewhere. I did make an effort to look around and did not see any previous discussion on the topic.

**Comment by ExperimentMonty** [comment]
+1 was surprised the first few times this happened. Especially since the web app has a create field for each category of items, not just one dropdown to create habits, tasks, etc.

**Comment by alexandreabeh** [comment]
+1
