### ISSUE TITLE
Due dates of to-dos are not Synced/Saved 

### ISSUE THREAD

**Issue by bhavin192** [HabitRPG/habitrpg-android#417]
Even after setting due date for to-do it's not synced with server (Site does not show the due date),
but if I set due date on site it's showed correctly in app.
 

ID
7dbae7f6-0692-4090-a650-f40f268e6318

**Comment by WhatsEmo** [comment]
I'll look into this

**Comment by ThiagoHenrik** [comment]
Whenever i set a date for a to-do and save, the date is reset for today.
