### ISSUE TITLE
website tutorial displays for accounts created in Android app

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitrpg-android#418]
If you create an account using the Android app and then log in to the website, you see the tutorial that new websites users are meant to get.

I.e., the tutorial on the website is intended for only new users who have just signed up on the website, however it's also being shown to players on the first time they used the website after signing up on the app.

**Comment by WhatsEmo** [comment]
Is this happening to the iOS app as well?

**Comment by vIiRuS** [comment]
No. It's likely happening because during registration the correct checks for the client aren't made. I'll look into that tomorrow.
