### ISSUE TITLE
No Mystic Hourglass

### ISSUE THREAD

**Issue by IceManX2X** [HabitRPG/habitrpg-android#437]
I have been waiting for my Mystic Hourglasses to come but it has been over a month from when I was supposed to receive it.  I started my subscription in October of last year but have not received my allotment of Hourglasses for 3 months yet.  Please help.

**Comment by IceManX2X** [comment]
My user ID is e01dcb6b-6239-40d1-a6e1-f3606d1109ef

**Comment by vIiRuS** [comment]
Hi,

Can You please write an email to admin@habitica.com, so that we can help you with this?
