### ISSUE TITLE
'Every X Days' dailies are wrongly displayed as due/not due

### ISSUE THREAD

**Issue by anowlcalledjosh** [HabitRPG/habitrpg-android#441]
I have a daily set to start on 2016-02-25 and repeat every 2 days; on the website, it correctly shows at not due today (2016-02-26), but it shows as due in the app. I'll check tomorrow and see if it reverses.

**Comment by anowlcalledjosh** [comment]
The behaviour is indeed the exact opposite of the website; when a daily is due, it's displayed as not due in the app and vice versa.

**Comment by ajfclark** [comment]
I also see this issue. I have a daily set to repeat every 3 days. It's due today, but the app will show it due tomorrow.

My cron time is 4am if that has any effect on things?
