### ISSUE TITLE
Missing gems

### ISSUE THREAD

**Issue by JerseyEmerald** [HabitRPG/habitrpg-android#459]
Hi is me, again, yes I realize I have a lot of issues and I had this issue last month. I used my android app to purchase gems, since you get 1 extra ☺ my first purchase went through but my second one didn't,  I didn't get a receipt either but it was taken from my bank account
Sorry to be a pain

**Comment by Alys** [comment]
You're not being a pain! This bug happens sometimes and I'm sorry it happened to you after all the other errors you've been getting. I've given you the 21 gems.

**Comment by JerseyEmerald** [comment]
I have them thank you!!
