### ISSUE TITLE
Consistent "connection error" messages and showing "[number]/1" for all my stats after latest app update

### ISSUE THREAD

**Issue by dbarnett** [HabitRPG/habitrpg-android#462]
The app lost the ability to sync after the recent 0.0.27.1 update (the one that added the Equipment view). My HP, XP, and MP all showed as being out of a total of one and every time I pulled up the app I immediately saw multiple "connection error" popups, with more every time I tried to sync. Website worked fine this whole time, and after I cleared app data and logged in again it resumed working normally.

**Comment by vIiRuS** [comment]
There seem to be a few other users that are also affected by this. So clearing the apps data from the android settings app fixed this for you? Or did you uninstall the app completely?

**Comment by dbarnett** [comment]
Correct, just cleared data, no uninstall (the "Clear Data" button here):
![image](https://cloud.githubusercontent.com/assets/65244/13840271/a90be3e2-ebde-11e5-9a98-5b8ac638f9b7.png)

**Comment by dbarnett** [comment]
Is there an app or backend update that fixes it? Or just fixed in the sense that a workaround is available?

**Comment by vIiRuS** [comment]
There will be a bugfix update early next week and I will to find a fix for this until then, so that people won't need to do this workaround anymore.
