### ISSUE TITLE
You can't remove a tag from a task

### ISSUE THREAD

**Issue by vIiRuS** [HabitRPG/habitrpg-android#474]
once assigned, a tag can't be removed from a task.

**Comment by jeubank12** [comment]
I'm thinking its somewhere in the Task.save() method.  Around 398 need to loop through all the tags rather than just the task tags.  Going to do some more debugging.  May add a remove task method to TaskTag

**Comment by jeubank12** [comment]
I don't yet understand the database well enough yet, but it seems that we never delete entries in TaskTag.java.  It only seems to add, from my comment above

**Comment by vIiRuS** [comment]
Yes, I also believe that that is the problem.

**Comment by alexfouche** [comment]
+1 I have this issue since at least 2 android updates of the app, and though each time that someone did know about it and that it would be fixed

**Comment by iupac98** [comment]
+1 I can't remove tags and they appear disorganized. Besides some tags that had been deleted appear again. This is very frustrating, as tags are necessary to set priorities and classify tasks. I hope you can sort it out soon, thanks!

**Comment by vIiRuS** [comment]
@iupac98 does this also happen with the most recent release? ( 0.0.30)

**Comment by iupac98** [comment]
Yes, actually after the recent update the problem has got worse, with all the tags disorganized...

El 24 de mayo de 2016 16:59:27 CEST, Phillip Thelen <notifications@github.com> escribió:
>@iupac98 does this also happen with the most recent release? ( 0.0.30)
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/HabitRPG/habitrpg-android/issues/474#issuecomment-221298984

-- 
Enviado desde mi teléfono con K-9 Mail.

**Comment by iupac98** [comment]
Actually, this worked properly in habitica before, but now I can't untag even from the website... this makes it very hard to prioritize and locate activities. Thanks!

**Comment by iupac98** [comment]
Let me add, as I recently noticed, that the tags are somehow removed and that can be seen when filtering, however the tag still appears (despite it's not functional).

**Comment by colinwirt** [comment]
From me, the task/todo edit UI shows tags that have been deleted. The deleted tags don't show on the filter list.

I'm planning to troubleshoot this issue, however haven't yet set up a development environment for this project, so can't promise I'll get around to resolving the problem. It would be nice to have a virtual machine that people like myself (a seasoned complex bug troubleshooter in enterprise systems) can dive straight into without the prohibitive step of setting up a development environment from scratch.
