### ISSUE TITLE
Party members equipment showing up in Equipment inventory

### ISSUE THREAD

**Issue by Redmega** [HabitRPG/habitrpg-android#492]
#### General Info
* Phone: Nexus 5X
* Android Ver: 6.0.1
* UUID: e2d15ef1-fb48-429d-ba54-646da01f4da7
* Group ID: 953304f9-f54c-42be-bb0a-c374e2eac540

#### Issue
I can see my (one) party members equipment in my equipment menu. When equipping it is attempted it gains the `Equipped` status and then a `Connection Error` occurs. When you navigate away from and then back to the equipment menu slot, the `Equipped` status is lost

#### Screenshots

![Leather Armor Equipped](https://lh3.googleusercontent.com/7jJouQwFceuKD-JbYbaaITHPFZBfN_2GPV5w6zMp-Zoveax0QEGKLFP0YBLtEObyIstty_jW2_t1=w459-h815-no)
![Leather Armor Connection Error](https://lh3.googleusercontent.com/FmUsR7GeeKWmt1XkEcaVgRHG5DkK5sLMaQuxME2QICitDsmfVVetsBJIWjA44ADeCBxLPAoes5hE=w459-h815-no)
![Leather Helm Equipped](https://lh3.googleusercontent.com/Un_bJzpU0tvzIQBPdkj_BvTLAYP6Kx-25pf0iUMXX1gXNOjs4BA_7vqD_7JY5clHWcsL5hlBHGSf=w459-h815-no)
![Leather Helm Connection Error](https://lh3.googleusercontent.com/iABCegEslVr2SDwLfhhQi1YwHzSgAftvIHNzt33ev1qwQ1YrEUwL_67kCs8QuQp_dtHwXJE_REpV=w459-h815-no)

#### Update
The party member purchased the mouse hat, and it appeared in my inventory, same connection bug with the others.

![Mouse Guard Helmet](https://lh3.googleusercontent.com/HgBgV4ipB4Rps99ilAquiyKK6grK7--6ahLl2S87f-OBASlKwFMBm5GUshZrgeIlJqURtdZNK5jzTvG53K1iobZy8RjPo0m6DS4zKp9bWaSSfMtxjkauPMKQUEIOY5ZMaDoiHzP2NArvv7_VEKRl1fpo6gS_bYYIaqf9BiSn8GEz2lNFlZJ2YWrzkm5lTu7sae2BN8q14LULuynLRLGC0tUidEVaYhTZP4cy5ZBS4xCfF-TqgHWT-kX9_c944eqv1kpbnoW-VlCiEppOJdk3bwLUVIW8RxpGO65Pq-omjUhRkoUvqWTe_oBKkYE-GNQlTr5JaGiDLSYuSm8fncb5dMkJtYSKweDQbykwlVUWynUB-C2LJtfBuPqs8iFElVbVDdFOgStOjubHxxtWLIb7DT5GCCZWUSkrJF7uDFjDGTTY9enTZxZxbPsdrp9NNW4lEOh8O4-a8o8jGjyEXKCsS5wxaAxDyX9mWi15rx2Vs-201eRDbdzlx1cgc1g9ukfSt-BWJeE8MmAs2RA87RmujEx19L9Y1Rro_kHrIV9WxS0AtQn7cOVDi-CzMJBlxQYYOQow=w450-h799-no)

**Comment by vIiRuS** [comment]
This was fixed through #481. The fix will be available in the next update.

**Comment by Redmega** [comment]
Oh cool, thanks :+1:
