### ISSUE TITLE
Viewing party members adds all of their equipment to your equipment list.

### ISSUE THREAD

**Issue by corpseboat** [HabitRPG/habitrpg-android#493]
[//]: # (Before logging this issue, look through common problems at https://github.com/HabitRPG/habitrpg/issue If you find your issue there, read at least the first post to see if there is a workaround for you.)

[//]: # (Github is primarilly used for reporting bugs. If you have a feature request, use "Help > Request a Feature" so that the feature request can be vetted by the larger Habitica community.)

[//]: # (To report a bug in one of the mobile apps, please report it in the correct repository. Android: https://github.com/HabitRPG/habitrpg-android, iOS: https://github.com/HabitRPG/habitrpg-ios)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitrpg/issues/2760 for more info)

[//]: # (Fill out relevant information - UUID is found in Settings -> API)
General Info
User 1
  * UUID: e6cd56f7-b0f2-4103-8b9f-f6c2f635806d
Android, samsung galaxy s3

User 2:
  * UUID: 7b251997-a7bc-402a-a5dd-02c99a978bc5
Android, ZTE Z933

Group ID: e4a70db3-a9f2-4c3d-a9f0-a265af971ba6

### Description
[//]: # (Describe bug in detail here. Include pictures if helpful.)

After starting a party and inviting a few other users, User 2 seems to have access to User 1's equipment items in their equipment screen. The access is not symmetric, User 1 at the beginning did not have access to User 2's inventory items. I've worked out some steps to reproduce it:

On my android app, I opened the equipment>head, and saw only my own gear. Then I opened party>members, and then opened equipment>head again, and saw my party member's gear as well as mine.

I then restarted my phone, and looked at my equipment without doing anything else, and the party member's gear was there still.

**Comment by corpseboat** [comment]
The items aren't equippable, it throws a connnection error, and the website version is unaffected.

**Comment by vIiRuS** [comment]
This was fixed with #481 and will be made available in the next app update.
