### ISSUE TITLE
Deleting tags from the filter tag list

### ISSUE THREAD

**Issue by abluescarab** [HabitRPG/habitrpg-android#496]
I see there's a call to a "delete tag" API function, but it hasn't been used. I was thinking maybe long-pressing in the filter tag list would be a way to delete a tag. I'm not sure if that meshes with Material Design guidelines, though.

Maybe instead there could be a button in the filter list that toggles between trash can icons and the switch. I'm kind of just throwing ideas against the wall right now and hoping one sticks.

**Comment by jjbillings** [comment]
I would like to work on this issue! I like both of the proposed ideas, but prefer the long-press. I am not super familiar with the material design guidelines, but would doing the long-press approach violate them?

**Comment by vIiRuS** [comment]
I don't think the guidelines say something against long presses, but they aren't good with discoverability. So many users would probably not figure out how to delete tags. Having an "Edit" button, that works similarly to the website (showing edit and delete icons for each tag) sounds good.

**Comment by jjbillings** [comment]
Great, I will give it a shot! Thanks for the help
