### ISSUE TITLE
Cannot access the British Bulldogs guild using app

### ISSUE THREAD

**Issue by Dewines** [HabitRPG/habitrpg-android#514]
I hope it's OK to raise this as a new issue? I mostly use a desktop computer, but now it's possible to access guilds, I'm increasingly making use of the Android app. I have it installed on both my Samsung phone and an Asus tablet. Mostly everything is fine, but for some reason I can't access the British Bulldogs guild. I always get the error message: "Connection error. There seems to be a problem with the server. Try again later." It seems odd that I only get this message on the British Bulldogs guild. It's also a problem that has persisted over a number of weeks, so it's not just coincidence that the server was wobbly just when I happened to look into this guild.I can't see anything different about the guild, so I am puzzled.Help please!

**Comment by Alys** [comment]
It does the same thing for me, very consistently (although I've only tested over the past half hour). How odd!

It does display the guild's description, but the list of chat messages is empty. However I'm able to send a chat message to the guild from the Android app (I confirmed that it appeared in guild chat on the website).

Guild link: https://habitica.com/#/options/groups/guilds/2374edb8-27fb-4138-a762-0cf1ae4ba676

**Comment by Alys** [comment]
In case it's relevant: The connection error happens before the gems balance has been displayed; I noticed that on other guilds, there'd be a delay before the balance was displayed, and the connection error happens within that delay for the British Bulldogs guild. However it doesn't seem to be related to the gems balance - when I change the balance from 4 gems to 0, the error still happens. I put the gems back afterwards. :)

**Comment by vIiRuS** [comment]
It's an issue with parsing the chat messages. The early messages seem to have an old format for the contributor field, that the app can't handle. This will be fixed in the next update.

**Comment by Dewines** [comment]
Thanks. That makes sense. The guild was so slow moving in the past that some of the messages are 3 years old.
