### ISSUE TITLE
Can't add a tag anymore

### ISSUE THREAD

**Issue by WillyReyno** [HabitRPG/habitrpg-android#522]
Hi, 

Everytime I'm trying to create a ToDo with a tag, the tag isn't saved. (And the same is happening when editing a ToDo)

**Comment by cleverscale** [comment]
+1 I have this issue since at least 2 android updates of the app, and though each time that someone did know about it and that it would be fixed

**Comment by alexfouche** [comment]
+1 I have this issue since at least 2 android updates of the app, and though each time that someone did know about it and that it would be fixed
