### ISSUE TITLE
App can be stuck in empty state

### ISSUE THREAD

**Issue by vIiRuS** [HabitRPG/habitrpg-android#538]
Some users seem to have an issue where their app is stuck in an empty state and never loads user data. Logging out and back in doesn't fix this, so it is probably something with the data in their account.

### EDIT:
If you are still experiencing this and want to help catch all instances of this issue, please provide us with your Habitica user ID.

**Comment by LuisGC** [comment]
I'm suffering this in my Nexus 4.

I can retrieve logs, test or try whatever is needed in my device. Just ask :-)

**Comment by easilver** [comment]
Same here on my G3

**Comment by barbellmel** [comment]
Having same issue on Samsung LG after recent updates. 
Habitica App worked well on my phone prior to updates. I have uninstalled, updated os and reinstalled the app a few times since then with no success.

**Comment by vIiRuS** [comment]
I believe I resolved this issue. I attatched a build (signed the same as a play store build) with the fix. It would be great if someone (or multiple people) could confirm that it resolves their issue.

[Habitica-release.apk.zip](https://github.com/HabitRPG/habitrpg-android/files/279775/Habitica-release.apk.zip)

**Comment by MorneArin** [comment]
Wooooorks! Grazie mille!

**Comment by magoo005** [comment]
I am having this issue, with both the release posted here, and the one available in the Google Play Store, 0.30.1

**Comment by vIiRuS** [comment]
@magoo005 hi, can you post your habitica user id either here or send it through the in-app bug reporting option?

**Comment by Volfaren** [comment]
Also having the same issue on v0.30.1
f22a7266-72df-4b46-86a1-a705fbb3420f

**Comment by walkerjd235** [comment]
- Having the same issue with Google Play version and the release posted here. 
- Side note: The version posted here does not allow me to log in by pressing the "Log-In with Facebook" button. When I log in using my email and password, the same error described previously occurs.
- This began earlier today after hitting Level 10 and choosing a class for the first time.

7da26742-4a40-431f-a611-1de4a222c08c

**Comment by aksnowman** [comment]
I believe I ran into this same issue. I'm running Android version 0.0.30.1 (86) from Google Play Store on a Samsung Note 5. Initially, I opened the app this morning to check on our party members health, but some of my stats would load intermittently (health seemed to always show, MP and XP would show the numbers, but the bars wouldn't consistently populate). The Rewards pane would populate correctly, but my Dailies pane wasn't showing anything reset after cron (though viewing via desktop browser shows they did). I tried: clearing cache, clearing all data, reinstalling the app. Clearing cache did nothing, clearing all data and then reinstalling the app both resulted in allowing me to log in, shows the header bar (HP/XP/MP/gold/gems/etc), but none are populated. The 4 panes that typically show don't show at all, and instead I just see the white/gray background rectangle with no icons/text/etc.

After switching to another section (guilds/etc) and back to Tasks, the headings of the 4 panes show (Habits, Dailies, Todos, Rewards), but still not populated with any data. Skills, Tavern, Party, Avatar, equipment, news shows blank with no headings. Guilds actually shows two guilds I am in, and I can enter them and see the respective chats. Items and Stable shows the respective headings (I assume they don't load dynamically?), but no items under any of the headings. While Party doesn't show anything in the pane, it does pop up an alert (modal?) saying "You are not in a party. To join a party, please visit the website." before showing nothing.

This seems to indicate that at least *something* is making it through (able to log in, and see my guilds), but obviously most is not.

Let me know if there is anything else I can do to give more info!

**Comment by vIiRuS** [comment]
@Volfaren @walkerjd235 In your cases it seems to be related to the quest your party is currently on. Will look into a fix tomorrow.

@aksnowman can you also tell me your habitica user id?

**Comment by aksnowman** [comment]
@vIiRuS Updated about a minute after I initially posted, realized I missed it, haha

**Comment by magoo005** [comment]
@vIiRuS I reported through the app after commenting on this bug.
User ID: 3bf052f9-5d48-42d6-9ccd-adeb8376809d

**Comment by dtyler** [comment]
I was seeing an issue where my tasks weren't syncing. In the course of my debugging I cleared my cache and app data. Afterwards I logged in again and the app was unable to load any of my stats or data. 

User Id: f6aa8774-ec0f-4ffb-9512-8d693a54792f

**Comment by vIiRuS** [comment]
We figured out the issue and will have it fixed shortly. There will be no update necessary, you will just have to refresh the app. We will update here when the fix is live.

**Comment by MichalangeloM** [comment]
Hello, I think I have an issue of this kind. In the app, everything that I think should have or say something is completely blank. I am able to log in, but the app doesn't load any of my data. I have a Wiko Rainbow Jam with Android 5.1, my User ID is: a1ed4c7b-3042-4839-a6bd-e69277494243

**Comment by crookedneighbor** [comment]
Hey all, this should be fixed now. Would y'all be kind enough to check for me?

**Comment by aksnowman** [comment]
Works for me! Even using skills which were giving me issues before! 





On Sun, Jun 5, 2016 at 7:38 PM -0700, "Blade Barringer" <notifications@github.com> wrote:












Hey all, this should be fixed now. Would y'all be kind enough to check for me?

**Comment by walkerjd235** [comment]
Fixed :) Thanks for the quick turnaround time.

**Comment by MichalangeloM** [comment]
It works now! Thank you very much!

**Comment by crookedneighbor** [comment]
For those interested, here is a technical blog post explaining what happened: http://devs.habitica.com/post-mortem-android-outage/
