### ISSUE TITLE
Mobile app crash

### ISSUE THREAD

**Issue by MorneArin** [HabitRPG/habitrpg-android#541]
After tasks synchronisation on my laptop mobile app on my android stopped working.
It shows nothing - no tasks, no habits, no stats, no profile picture.
Login/log out doesn't help, as well as deinst/installation.

**Comment by vIiRuS** [comment]
Did the app crash and then start not displaying data or did it just start not displaying data? What is your habitica user ID?

**Comment by MorneArin** [comment]
I've created my habitica acc through the mobile app, then edited it on my laptop. After it refused to sync on the app I logged out/logged in again and that was the point where the problem has arised.
7424e96f-403c-4cb7-941d-8ec565468bea

**Comment by vIiRuS** [comment]
This is the same issue as #538
