### ISSUE TITLE
Switch to realm?

### ISSUE THREAD

**Issue by vIiRuS** [HabitRPG/habitrpg-android#542]
Since DBFlow is causing a few issues and is generally not as actively developed as realm is, I'm considering to switch.
Do other people have experience/opinions on realm?

**Comment by mgranberry** [comment]
My experiences with Realm in the last 6 months are all quite positive.  There used to be some serious threading issues around short-lived connections to the database, but it appears that the race conditions have been discovered and corrected.  

Migrations are still a pain even with the new APIs, but they are much better than they were before.

The old restrictions around doing actual OOP in RealmObjects are all gone now, so the restrictions there should only involve minimal pain now.

My biggest complaint is probably that there is a 3k-method penalty for including it in a project.
  
The query language is fairly easy to learn and become productive in.  The only problems there are some strange results when trying to perform a distinct on an async query, which is probably an esoteric edge case bug that I found.

I love that I can initiate an async query on the main thread and have it trigger an update and notification when it finishes, never worrying about performance (which is quite good -- for some projects you can get away with doing all work on the main thread, although you shouldn't).

I also like that it is fairly easy to integrate with the [Data Binding Library](https://developer.android.com/topic/libraries/data-binding/index.html) to make a lot of UI state propagation tasks easier.

**Comment by vIiRuS** [comment]
I started working on a plan to switch over to realm and will start working on that in the next weeks.
