### ISSUE TITLE
Authentication failing on v0.0.30

### ISSUE THREAD

**Issue by acmiyaguchi** [HabitRPG/habitrpg-android#544]
I am encountering two separate bugs with an existing account attached to a Facebook account, one from the login page and one from the register page. I attempt to log in using both Facebook and a local login. This bug first occurred when upgrading to 0.0.30 while still logged in, and then logging out sometime after the update.

* When attempting to authenticate from the login page with both authentication methods, I am redirected to the main screen of the app with an empty profile picture, and 0 hp/mp/exp. There are no loaded tasks of any kind.
* When attempting to authenticate from the register page with Facebook, I am put through the beginner screen despite having an existing account. I am then redirected to the main screen with the correct avatar information. Existing tasks are not synced to the app. Creating new tasks however remain in the app's list and get synced to the web version.

I am on 0.0.30 on android 5.0.2, uuid c9992e29-c018-44d5-8f7e-af679dad9632.

**Comment by Backhell** [comment]
Hi acmiyaguchi, i encounter the same problem, after the recent update my app (version 0.0.30 on android 6.0.1) did not synch with web version so i uninstalled app and reinstalled it.
Now the app only shows 0/hp/mp/exp, no tasks/rewards/items (only blank screen).
Guild does load after a while, but app crashes if i try to click on it...

Hope there is someone who can help me with this

Thanks in advance an a nice Day
Backhell

**Comment by vIiRuS** [comment]
This is a case of #538  and will be resolved with the next update, which we will release soon.

**Comment by Backhell** [comment]
Thanks alot vliRuS
Sorry didn't see bug report #538 or i would have commented there.

Have a nice day
