### ISSUE TITLE
Connection Error when Using Blessing

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitrpg-android#550]
" I can use all but one of my skills without the app crashing. Every time I try to cast my group heal it will say something about their being a network error and it won't work. All the other spells and group spells work fine."
Device: trltevzw 
Android Version: 22 
AppVersion: Version 0.0.30.1 (85) 
User ID: 248a716e-efad-480b-9b58-9e3f8907fb1f 

After update requested:

"App updated to newest version and still can't cast the party heal spell without getting an error. Pics of this!"

![screenshot_2016-05-26-23-25-12](https://cloud.githubusercontent.com/assets/3494081/15623908/2e8208ba-2430-11e6-8705-f9ad425cec69.png)

**Comment by gabeos** [comment]
I am receiving the same issue on thethe latest android app, LG G4 phone.
