### ISSUE TITLE
After equipment purchase, gold does not update visually.

### ISSUE THREAD

**Issue by djchateau** [HabitRPG/habitrpg-android#555]
When you purchase a piece of equipment the amount of money on the screen does not change. If you then try to purchase another piece of equipment, you are presented with an error indicating you do not have enough gold. This seems to imply it's correctly subtracting the right amount where the value of your hold is stored but the app is not reporting to the user how much they actually have.

![screenshot_2016-06-03-14-16-58](https://cloud.githubusercontent.com/assets/1657434/15789877/6c201812-299c-11e6-9031-0698dd3968ff.png)
![screenshot_2016-06-03-14-17-02](https://cloud.githubusercontent.com/assets/1657434/15789883/71455488-299c-11e6-8b21-c00615dbd3b8.png)

**Comment by mandyzhou** [comment]
As a temporary workaround, you can tap the sync button (the circular arrow in the top right corner) and the gold amount should update.
