### ISSUE TITLE
chat messages cannot be copied to clipboard (Tavern, guilds, party)

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitrpg-android#557]
It would be useful if chat messages could be copied to the clipboard. This would allow players to repost a message they'd made that contained a mistake

**Comment by jjbillings** [comment]
Hello! I would like to begin contributing to this project. Would this be a good issue to start on?

**Comment by vIiRuS** [comment]
Yes, this should be a good issue to start on!

As a starting point, the menu items for chat messages are handled here: https://github.com/HabitRPG/habitrpg-android/blob/develop/Habitica/src/main/java/com/habitrpg/android/habitica/ui/adapter/social/ChatRecyclerViewAdapter.java#L426
