### ISSUE TITLE
quest participants don't show on Party screen until Members screen is loaded

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitrpg-android#562]
When I'm in a quest (either active or in the invitation stage), the quest information will appear on the "PARTY" screen but the participants won't.

If I then go to the "MEMBERS" screen and back to the "PARTY" screen, then the participants appear.

I.e., the quest participant details aren't loaded unless you load the members list.

**Comment by vIiRuS** [comment]
This is the same issue as #551
