### ISSUE TITLE
Query: What is the behaviour for adding a reminder to a task(daily/todo)

### ISSUE THREAD

**Issue by jonyeezs** [HabitRPG/habitrpg-android#580]
I have tried adding a reminder to a task, but i seem to be getting notifications of "Please check your dailies" But nothing on the actual reminder times and no notification that shows specifically which task triggered that notification.

I would like to know the actual behaviour I should be expecting for adding a reminder.

**Comment by vIiRuS** [comment]
The "Please check your dailies" is the reminder that is configured through the apps settings.
Dailiy reminders are displayed at the configured time on all days that daily is active.

**Comment by jonyeezs** [comment]
I guess the daily reminders didn't work for me. I had the configured time but no notifications appeared.
I even had notifications settings to priority.

I've just updated my version so can't remember what was the previous.

Though now i have a new problem which i've logged: #579

**Comment by jonyeezs** [comment]
Now fixed in version 0.0.32.1 (105)
