### ISSUE TITLE
Koodous marks it as dangerous

### ISSUE THREAD

**Issue by cmmata** [HabitRPG/habitrpg-android#594]
[Koodus antivirus](https://play.google.com/store/apps/details?id=com.koodous.android) is currently showing Habitica as dangerous / possible malware. Did you change something in last release? I have both apps installed for months, and I didn't see that message in all past scans.

By the way, I installed it from Google Play, not directly.

**Comment by vIiRuS** [comment]
Does the app provide any further indication as to why habitica was flagged like this?

The last update added push notifications using firebase. But I don't see how that would cause it to be marked as dangerous.

**Comment by cmmata** [comment]
No, it doesn't say anything more than it's a potential risk. The only option it gives to you is to uninstall the app. I tried to uninstall it and install again from Play Store, and now it says it's ok, no malware. Maybe there was a problem with previous version and not with Play Store's last one.

This app works with a community at koodous.com, so I suppose anyone marked previous version as potential malware.

So at this moment the solution looks like to update the app, or directly reinstall it. I'll let you know if it's flagged again as dangerous.
