### ISSUE TITLE
Android stopped working after update

### ISSUE THREAD

**Issue by crookedneighbor** [HabitRPG/habitrpg-android#598]
Originall reported at https://github.com/HabitRPG/habitrpg/issues/7905 by @Olia1 

> - sorry for posting in the wrong section, but I can't figure out how to post an issue at the android section from my phone. 

> - I have updated the app to version 0.33.1, and the app has stopped working. It crashes about 2 sec after opening it. 

> - tech details :
> Android 5.1.1

**Comment by vIiRuS** [comment]
@Olia1 can you tell me your habitica user ID? You can find that on the website by opening the "API" page from the settings menu at the top right.

**Comment by Olia1** [comment]
Thank you for opening the issue at the proper place, and sorry for the trouble. I also apologise for forgetting to include the API

3f6a57c5-9321-408b-8ed6-db58dde1ad5a

**Comment by vIiRuS** [comment]
The issue you have will be fixed in the next app update and you should also be able to fix it for yourself, by clearing the app data through androids settings and then logging in again.

**Comment by Olia1** [comment]
@vliRuS thank you very much! It works now!
