### ISSUE TITLE
count of pets is too high

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitrpg-android#607]
I have about 445 pets but the Android app reports that I have 2507 pets. If you add up all the feed values of my pets, it comes to 2507 so I think that's what the app's doing.

I've also seen reports of pet counts being incorrect on iOS so it might be doing the same thing too.

**Comment by vIiRuS** [comment]
Which pet count are you referring to? The number in the profile?
(The iOS app doesn't have the pet count in the profile yet, so it wouldn't be the same issue)

**Comment by Alys** [comment]
Sorry, yes, the number in the profile. I couldn't find any other pet count so I thought that was the only one. My bad - I should have specified anyway.

I'll keep trying to get iOS users to give us more information about their problem. I've only seen a couple of reports that were definitely iOS so it might be nothing.

**Comment by mandyzhou** [comment]
Same issue here -- I have 221 pets but my profile in the Android app reports 565.

**Comment by Alys** [comment]
@vlad-vassilovski Great summary! The website is correct in the way that it counts pets.

**Comment by vlad-vassilovski** [comment]
Thanks, Alys.

I may be able to put a PR for this up within a week or two - just looking at some other obligations first.

Of course, if anyone needs or wants to get a fix in faster than that, feel free to do so.

**Comment by vlad-vassilovski** [comment]
Actually, this was fixed a few days ago - https://github.com/HabitRPG/habitrpg-android/commit/b6ebd58d11355000c911d849dcd9338887c0db58

I assume this issue can be closed.

**Comment by Alys** [comment]
@vlad-vassilovski I'm sorry your time was wasted. :(
