### ISSUE TITLE
Health potion listed under Costume in my profile

### ISSUE THREAD

**Issue by mandyzhou** [HabitRPG/habitrpg-android#608]
Under my profile, one of the items listed under Costume is the health potion:

![2016_08_28_11 23 14](https://cloud.githubusercontent.com/assets/279805/18037022/36a91004-6d48-11e6-9265-089c28733972.png)

**Comment by DanielKaparunakis** [comment]
Where is this profile screen?

**Comment by vIiRuS** [comment]
You can access someones profile by tapping their name in any chat message. (similar to how it is on the website)

**Comment by goldfndr** [comment]
For me, it also appears in my Battle Gear. It also (currently) appears in the profile for "citrusella, the serving wench" in her Battle Gear.
