### ISSUE TITLE
Distribute through F-Droid / build without Google

### ISSUE THREAD

**Issue by h-2** [HabitRPG/habitrpg-android#612]
Dear devs,

I would really love to see Habitica in F-Droid. In case you don't know, F-Droid is a community driven appstore for Android with a focus on the privacy, security and freedom of its users.
Since Habitica is Free Software, it should be no problem to include it. I have opened a ticket at F-Droid here:
https://f-droid.org/forums/topic/habitica-formerly-habitrpg/

However for F-Droid it is required that tools not depend on Google Play Services and the Google Push API (since the programs need to work on Google-free Android phones, as well). Do you have a mechanism for building Habitica without this dependency or could you add it? In case you use the Push API to inform the client about changes, could you implement a fallback to a periodic pull, e.g. every 15min? Many programs do this as a fallback automatically on non-Google platforms. It would probably also increase portability to other stores or non-Android platforms like Ubuntu Phone....

Thank you very much in advance!

**Comment by vIiRuS** [comment]
We already have an issue for this at #194 I a contributor is interested in working on this, they can feel free to do so.
